### ISSUE TITLE
Pulumi provider for sentry.io

### ISSUE THREAD

**Issue by henriiik** [pulumiverse/.github#18]
I want to create a pulumi provider for [Sentry.io](http://sentry.io/) based on this terraform provider: https://registry.terraform.io/providers/jianyuan/sentry/latest/docs.

**Comment by rawkode** [comment]
@henriiik i can help 😀

we made a video on this to provide some guidance, but I’d be happy to assist you also - either with advice or code

https://youtu.be/ZjTFaqMrYvY

Let me know what you need 🙏

**Comment by ringods** [comment]
@henriiik the empty repository is created, and you are added as a member to it. You should be able to start contributing via PRs.

**Comment by henriiik** [comment]
@ringods Thanks!

I have created a PR https://github.com/pulumiverse/pulumi-sentry/pull/1, i added you as the reviewer should i add someone else in addition / instead?

**Comment by ringods** [comment]
It's OK for now. Long term, I hope you can attract more community participation to your provider and promote at least a second person as co-maintainer. When the community grows, I won't have the time to review all contributions and neither is it the intent as a Pulumiverse board member.

For now, welcome to our community and a thank you already for the work you want to contribute! 👍🏻
