### ISSUE TITLE
Please create a bot user for each package registry

### ISSUE THREAD

**Issue by jaxxstorm** [pulumiverse/.github#22]
The current publish keys are linked to @ringods's user account which means all publishes appear to be from him

![image](https://user-images.githubusercontent.com/1622940/187556607-8cc8eadc-1cb7-4b4f-8e8a-470c18ffbc76.png)

This has a few problem implications, not least that it violates the bus factor.

My suggestion would be to create a `pulumiverse-bot` user for each of the package registries and place the details in 1password so they can be shared

**Comment by simenandre** [comment]
I agree! We should probably set up something like [wombat-dressing-room](https://github.com/GoogleCloudPlatform/wombat-dressing-room) for NPM (proxy, one token per repo).

**Comment by jaxxstorm** [comment]
That seems like a reasonable long term goal, but my biggest concern right now is that my hard work is being passed off as someone else's, which makes me sad and less likely to contribute to the pulumiverse.

A bot user is clearer

**Comment by simenandre** [comment]
Yes, I agree.

**Comment by ringods** [comment]
@jaxxstorm we will discuss the technical setup during our upcoming board meeting.

**Comment by simenandre** [comment]
I have claimed the NPM user for this, and will continue to set this up soon 👍

**Comment by ringods** [comment]
This is in place now.
