### ISSUE TITLE
Migrate `pulumi-buildkite` provider to Pulumiverse organization

### ISSUE THREAD

**Issue by christophermaier** [pulumiverse/.github#28]
I currently maintain the [pulumi-buildkite](https://github.com/grapl-security/pulumi-buildkite) provider through my employer, but we will unfortunately not be able to continue maintaining it. As such, we would like to donate it to the Pulumiverse organization to ensure it remains available for the broader Pulumi community.

**Comment by ringods** [comment]
@christophermaier thanks for creating the last release of the provider so the users are informed.

We can start the migration process now. Can you use `Transfer ownership` to transfer the repo to me? I will move it forward to the `pulumiverse` organization.

**Comment by christophermaier** [comment]
@ringods I've initiated the transfer (it'll be coming from my personal account).

**Comment by ringods** [comment]
Accepted. Thank you.

**Comment by ringods** [comment]
@christophermaier if you have the build setup for this provider still active in your Buildkite setup, feel free to remove it.
