### ISSUE TITLE
Pulumi provider for StatusCake

### ISSUE THREAD

**Issue by jgautheron** [pulumiverse/.github#30]
I want to create a pulumi provider for [StatusCake](https://www.statuscake.com/) based on this terraform provider: https://registry.terraform.io/providers/StatusCakeDev/statuscake/latest/docs.

**Comment by ringods** [comment]
@jgautheron I will set you up with the repository. Thank you very much upfront for the contributions!

**Comment by ringods** [comment]
Setup of infrastructure: https://github.com/pulumiverse/infra/pull/57

**Comment by ringods** [comment]
@jgautheron you will shortly receive an email invite to join the Pulumiverse Github organization. Welcome!!
