### ISSUE TITLE
Pulumi provider for PGSSoft/terraform-provider-mssql

### ISSUE THREAD

**Issue by tmeckel** [pulumiverse/.github#31]
I want to provide a Pulumi Provider based on the [PGSSoft/terraform-provider-mssql](https://github.com/PGSSoft/terraform-provider-mssql) Terraform provider. 

Docs: https://registry.terraform.io/providers/PGSSoft/mssql/latest/docs

Can someone create a new repo for it in Pulumiverse and add me as a contributor? 😃

**Comment by ringods** [comment]
@tmeckel can you create a PR in https://github.com/pulumiverse/infra similar to [this one](https://github.com/pulumiverse/infra/pull/58/files)?

**Comment by tmeckel** [comment]
@ringods Of course. Just for my personal information, did I miss any documentation on this i.e. how to request a new repo?

**Comment by ringods** [comment]
@tmeckel no, you didn't. We have to work on this!

**Comment by tmeckel** [comment]
@ringods PR created -> https://github.com/pulumiverse/infra/pull/59
