### ISSUE TITLE
Build a new provider for the VMware ESXi hypervisor

### ISSUE THREAD

**Issue by edmondshtogu** [pulumiverse/.github#33]
Build a new provider for the VMware ESXi hypervisor to provision VMs directly on an ESXi hypervisor without a need for vCenter or vShpere.

In case we want to build a home lab on-prem infrastructure using ESXi, to provision it with Pulumi we need to install rather vSphere or vCenter as the current provider by vSphere doesn't support the ESXi management directly.

**Comment by ringods** [comment]
Hello @edmondshtogu, do you want to contribute building by bridging [this Terraform provider](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs)? If so, we can help set you up with a repository here and help you getting it published in our Pulumi registry.

**Comment by edmondshtogu** [comment]
Hi @ringods I am building a native one actually, so far I have created this [repository](https://github.com/edmondshtogu/pulumi-esxi-native) where I have been developing the functionality but I would like to rather add it to pulumi registry, or set it up under pulumi org.

**Comment by ringods** [comment]
@edmondshtogu we can get this into Pulumiverse. Can you transfer the repo to me (GH `ringods`) and I will move it further into the `pulumiverse` GH organization.

**Comment by edmondshtogu** [comment]
@ringods I did initiate the transfer, please as this is done then add me as a contributor there so I can continue working on the remaining functionalities.

**Comment by ringods** [comment]
Repo migrated into Pulumiverse.

Still need to import the setup into the Pulumi managed setup: https://github.com/pulumiverse/infra/pull/75
