### ISSUE TITLE
pulumi-vercel

### ISSUE THREAD

**Issue by omercnet** [pulumiverse/.github#36]
now that the tf plugin bridge is working I'd like to contribute my bridge to vercel
this is following up on https://github.com/pulumi/pulumi/issues/7615

my repo is here https://github.com/omercnet/pulumi-vercel and is still a work in progress but should be ready for publication later this week

**Comment by omercnet** [comment]
https://github.com/omercnet/pulumi-vercel is ready, how do we get it into pulumiverse as a proper package?

**Comment by ringods** [comment]
Hello @omercnet, happy to see you joining forces. To initiate the process of bringing your provider under the Pulumiverse wings, please start the transfer of the repository to me. I will move it further to `pulumiverse`. 

You will retain all rights along the way and remain the primary caretaker.

**Comment by omercnet** [comment]
> Hello @omercnet, happy to see you joining forces. To initiate the process of bringing your provider under the Pulumiverse wings, please start the transfer of the repository to me. I will move it further to `pulumiverse`.
> 
> You will retain all rights along the way and remain the primary caretaker.

gladly, but I'm getting this error

You don’t have the permission to create public repositories on pulumiverse

**Comment by omercnet** [comment]
Repository transfer to ringods requested

**Comment by ringods** [comment]
@omercnet the repo is migrated: https://github.com/pulumiverse/pulumi-vercel

Please update the package namespaces and prefixes to read `pulumiverse` before publishing new releases. Here is the info on it:
https://github.com/pulumiverse/infra/blob/main/README.md#package-registries
